
import scraped from "../data/providers.json"; // generated by the scraper

const FALLBACK = [
  {
    id: "demo-neo",
    name: "NeoBuild Technologies",
    location: "Riyadh",
    rating: 4.7,
    reviews: 128,
    baseCost: 1200000,
    costPerSqm: 4500,
    timelineSpeed: 0.9,
    tech: ["3D Printing", "Prefabrication", "AI QC"],
    pastProjects: 42,
    photos: [
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1400&auto=format&fit=crop",
    ],
  },
  {
    id: "demo-sky",
    name: "SkyRise Modular",
    location: "Jeddah",
    rating: 4.5,
    reviews: 94,
    baseCost: 900000,
    costPerSqm: 3800,
    timelineSpeed: 0.8,
    tech: ["Modular", "Prefabrication", "BIM"],
    pastProjects: 51,
    photos: [
      "https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?q=80&w=1400&auto=format&fit=crop",
    ],
  },
];

function normalize(p, idx) {
  const photos = Array.isArray(p.photos) ? p.photos : [];
  const logo = typeof p.logo === "string" && p.logo.trim() ? p.logo.trim() : null;
  const mergedPhotos = photos.length ? photos : (logo ? [logo] : []);

  return {
    id: p.id || `mbt-${idx + 1}`,
    name: p.name || p.company || "Provider",
    location: p.city || p.location || "KSA",
    rating: Number(p.rating) || 4.4,
    reviews: Number(p.reviews) || 0,
    baseCost: Number(p.baseCost) || 900000,
    costPerSqm: Number(p.costPerSqm) || 3800,
    timelineSpeed: Number(p.timelineSpeed) || 0.85,
    tech: Array.isArray(p.tech) ? p.tech : [],
    pastProjects: Number(p.pastProjects) || 0,
    photos: mergedPhotos, // prefer logo if no photos
    logo: logo,
    url: p.url || null,
    website: p.website || null,
    phone: p.phone || null,
  };
}

const HAS_SCRAPED = Array.isArray(scraped) && scraped.length > 0;
export const PROVIDER_SOURCE = HAS_SCRAPED ? "scraped" : "fallback";
export const PROVIDERS = HAS_SCRAPED ? scraped.map(normalize) : FALLBACK;